Se agregan queries custom a repo de book y user
wolox-training/rm-java pull request #12
Opened 2020-05-15 21:27 UTC by rem86

Se agregan parametros opcionales en los queries de los repo Book y User 
Card: https://trello.com/c/vLFzcNuX/22-queries-custom-en-repositorio

2020-05-18 14:44 UTC, Gianni-Nicolas requested changes
Muy buen trabajo 👍. Solo deje unos pocos comentarios 😄

2020-05-18 14:44 UTC, GNico95 commented on .idea/.gitignore
> +/workspace.xml
Agregar la carpeta .idea al git ignore para que no aparezcan en el PR.

2020-05-18 14:44 UTC, GNico95 commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    @Query("SELECT u FROM Book u WHERE (:pub <= '' or u.publisher = :pub) and (:gen <= '' or"
En la query en vez comparar a las distintas variables con empty se compara contra null. Se podría hacer algo como esto:

```suggestion
    @Query("SELECT u FROM Book u WHERE (:pub is null or u.publisher = :pub)"
            + " and (:gen is null or u.genre = :gen)"
            + " and (:yea is null or u.year = :yea)")
```

2020-05-18 14:44 UTC, GNico95 commented on src/main/java/wolox/training/repositories/UserRepository.java
> +        + "(:bf is null or u.birthdate <= :bf) and (:na <= '' or upper(u.name) = upper(:na))")
La comparación de fechas se podría facilitar con la sentencia between, y el nombre también se compararía contra null y no contra empty. Se podría hacer algo como esto: 
```suggestion
	@Query("select u from User u where ((cast(:bi as date) is null or cast(:bf as date) is null or"
	        + " u.birthdate between :bi and :bf) and (:na is null or lower(u.name) like lower(concat('%',:na,'%'))))")
```

2020-05-18 15:26 UTC, rem86 commented on .idea/.gitignore
> +/workspace.xml
Tolis!!

2020-05-18 15:27 UTC, rem86 commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    @Query("SELECT u FROM Book u WHERE (:pub <= '' or u.publisher = :pub) and (:gen <= '' or"
Lo probe asi, pero no me funcó desde PostMan!!.. Por eso lo deje con el <=...

2020-05-18 15:36 UTC, rem86 commented on src/main/java/wolox/training/repositories/UserRepository.java
> +        + "(:bf is null or u.birthdate <= :bf) and (:na <= '' or upper(u.name) = upper(:na))")
Buenisimo!!! ahi lo modifique!

2020-05-19 16:09 UTC, Gianni-Nicolas approved these changes

2020-05-19 16:50 UTC, merged