Se agrega modelo Book
wolox-training/rm-java pull request #3
Opened 2020-04-27 18:16 UTC by rem86

Se agrega modelo Book.
Card de trello: https://trello.com/c/yL1w6DBx/8-crear-modelo-de-book

2020-04-27 20:24 UTC, leandrocostawolox requested changes
Genial, Ricky! Te dejo unos comentarios para ajustar un par de cuestiones :)

2020-04-27 20:24 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +    private String genre;
En este caso, el género no es requerido, así que podría obviarse la annotation :)

2020-04-27 20:24 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +    private String isbn;
Estos campos que sí son requeridos podrían la annotation `@NotNull` (de javax.validation.constraints.NotNull) que les comenté. La diferencia está en que con @NotNull JPA entra en acción atajando nulls antes de que lleguen a la base de datos (Con @Column(nullable = false) la validación directamente se haría en la base de datos). Si bien en el link de la card se utiliza `@Column`, vamos a preferir `@NotNull` para estos casos así evitamos el chequeo en la DB 👍

2020-04-27 20:24 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +	}
El `id` de nuestros objetos lo va a manejar JPA, entonces queremos que sea lo más inmutable posible y que no pueda modificarse para evitar problemas. Por esto, lo mejor sería no tener un setter para el `id`

2020-04-27 20:24 UTC, leandrocostawolox commented on src/main/java/wolox/training/models/Book.java
> +    }
Genial! Agregaría también un constructor por defecto (el vacío) porque lo necesita JPA para luego construir objetos:
```
public Book() {

}
```

2020-04-27 20:24 UTC, leandrocostawolox commented on pom.xml
> +
Estas dependencias no son necesarias, cuando creamos el proyecto se nos generó el pom.xml con la dependencia `spring-boot-starter-data-jpa` (línea 59 si no me equivoco), con esa ya es suficiente 😄

2020-04-27 20:30 UTC, rem86 commented on pom.xml
> +
Joya!! las vuelo...

2020-04-27 20:31 UTC, rem86 commented on src/main/java/wolox/training/models/Book.java
> +    }
Agregado!

2020-04-27 20:32 UTC, rem86 commented on src/main/java/wolox/training/models/Book.java
> +	}
Verdad. Vuelan!. Lo dijiste el otro dia...

2020-04-27 20:38 UTC, rem86 commented on src/main/java/wolox/training/models/Book.java
> +    private String isbn;
Joya! Lo cambio...

2020-04-27 20:43 UTC, rem86 commented on src/main/java/wolox/training/models/Book.java
> +    private String genre;
Perdón! Corregido!

2020-04-27 20:56 UTC, rem86 reviewed
Envie un PR con los cambios! Gracias!

2020-04-27 23:46 UTC, rem86 reviewed
No había agregado al commit ni el pom.xml ni TrainingApplication.java . Agregados!

2020-04-28 00:53 UTC, leandrocostawolox approved these changes
Geniial! Ahora sí, mergealo cuando quieras! :)

2020-04-28 12:23 UTC, rem86 commented
Ok! gracias!!

2020-04-28 12:24 UTC, merged