Se agrega el controller user
wolox-training/rm-java pull request #8
Opened 2020-04-30 21:24 UTC by rem86

-Se crea controller.
-Se adapta modelo para que funcione addbook y removebook.
-Se agregan excepciones.
Card: https://trello.com/c/wur9Vmzi/15-crear-user-controller-con-las-operaciones-crud-de-user

2020-05-05 13:47 UTC, leandrocostawolox requested changes
Joya, Ricky! Te dejé unos comentarios, cualquier cosa avisame!
Te quedaron tabs en lugar de espacios en algunas partes de lo commiteado 🤔 Puede ser por un copy paste de la clase BookController. No hay drama igual! Pero chequeemos que no pase más adelante así ya nos queda bien para el proyecto :)

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +	@GetMapping("/")
No es necesario el `("/")`, el GET lo haríamos directamente sobre la ruta padre definida al principio de la clase como `@RequestMapping("/api/users")`
O sea, quedaría como el anterior: `@GetMapping`

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    public Optional<User> findByAuthor(@RequestParam(required = true) String username) {
El nombre del método sería `findByUsername` (Creo que es un error de copy paste jaja)

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +        return userRepository.findFirstByUsernameOrderByIdAsc(username);
Acá podrías usar un `orElseThrow` como hiciste en el método siguiente para mostrar un 404 con un mensaje en el caso de no encontrar usuario

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +import wolox.training.repositories.*;
Creo que te faltó hacer lo de la guía de configuración del IDE, por eso está este import con `*`

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    @PostMapping("/{id}/addbook")
La forma más REST de hacer esta ruta sería
`@PostMapping("/{id}/books/{bookId}")`
O sea, un post de un libro del usuario. No es necesario recibir el book como body, sino más bien sólo el id del libro (El libro se supone que ya fue guardado haciendo un POST a api/books

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    @PostMapping("/{id}/removebook")
La forma más REST de hacer esta ruta sería
`@DeleteMapping("/{id}/books/{bookId}")`
O sea, un delete de un libro del usuario. No es necesario recibir el book como body, sino más bien sólo el id del libro

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    	user = userRepository.findById(id)
La primer línea no es necesaria, podemos evitar instanciar un User y directamente obtenerlo desde la base:

`User user = userRepository.findById(id)...`

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +    	user = userRepository.findById(id)
La primer línea no es necesaria, podemos evitar instanciar un User y directamente obtenerlo desde la base:

`User user = userRepository.findById(id)...`

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +}
El warning de la falta de un salto de línea creo que también es porque falta hacer lo de la guía que les pasé

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/exceptions/UserIdMismatchException.java
> +	}
Si no usamos los tres constructores conviene dejar sólo los que usamos. En caso de necesitarlos luego los podemos ir agregando :) 
Esto es para minimizar la forma de crear objetos, permitiendo crearlos sólo en base a lo que nuestro sistema requiere

2020-05-05 13:47 UTC, leandrocostawolox commented on src/main/java/wolox/training/exceptions/UserNotFoundException.java
> +    }
Si no usamos los tres constructores conviene dejar sólo los que usamos. En caso de necesitarlos luego los podemos ir agregando :) 
Esto es para minimizar la forma de crear objetos, permitiendo crearlos sólo en base a lo que nuestro sistema requiere

2020-05-05 18:47 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +	@GetMapping("/")
Corregido!!

2020-05-05 18:49 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +    public Optional<User> findByAuthor(@RequestParam(required = true) String username) {
jajajaja ! corregido!

2020-05-05 18:55 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +        return userRepository.findFirstByUsernameOrderByIdAsc(username);
Perfecto! lo dejo consistente...

2020-05-05 18:56 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +import wolox.training.repositories.*;
Sip... Listo!.

2020-05-05 18:59 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +    @PostMapping("/{id}/addbook")
Ok! Modificado!.

2020-05-05 19:00 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +    	user = userRepository.findById(id)
Ah, ok! Lo sumo... Grs!

2020-05-05 19:08 UTC, rem86 commented on src/main/java/wolox/training/controllers/UserController.java
> +    	user = userRepository.findById(id)
Listo!

2020-05-05 19:11 UTC, rem86 commented on src/main/java/wolox/training/exceptions/UserIdMismatchException.java
> +	}
Perfecto!

2020-05-05 19:11 UTC, rem86 commented on src/main/java/wolox/training/exceptions/UserNotFoundException.java
> +    }
Listo!

2020-05-06 18:20 UTC, leandrocostawolox requested changes
Joya todo lo de CRUD de User! 
Pero un detalle, se te escapó un commit de testing en este mismo PR. Convendría que lo vuelvas atrás (O elimines la clase y luego la crees en el branch que corresponde)
Así separamos en dos PRs distintos lo de CRUD User y lo de tests :)

2020-05-06 18:50 UTC, leandrocostawolox approved these changes
Genial! 😄

2020-05-06 18:50 UTC, rem86 commented
Ups!. Ahi lo saque desde la pagina git!. Gracias!!

2020-05-06 18:56 UTC, merged